# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/checkout@v2
        with:
          repository: adaptusnow/adapt-testing-smoke-testsuite
          ref: 'develop'
          token: ${{ secrets.token }}

      - name: Change dir
        run: |
          cd AdaptAPITesting
          pwd
          ls -lrt
      - name: Build with Maven
        run: mvn -f /home/runner/work/test_repo/test_repo/AdaptAPITesting clean install
#       - name: GitHub Action for Maven
#         if: ${{ success() }}
#         uses: LucaFeger/action-maven-cli@1.1.0
#         with:
#           args: -f /home/runner/work/test_repo/test_repo/AdaptAPITesting/pom.xml clean install
